RedHatInsights/insights-results-aggregator-exporter

- abcgo.sh
- goconst.sh
- gocyclo.sh
- goerrcheck.sh
- gofmt.sh
- golint.sh
- gosec.sh
- govet.sh
- ineffassign.sh
- shellcheck.sh
> Linter scripts

- Makefile
- README.md
> Makefile + doc

- config.go
- config_test.go
- exporter_test.go
- logging.go
- logging_test.go
- s3.go
- storage.go
- storage_test.go
- types.go
> Stub for project

- docs/packages/config.html
- docs/packages/config_test.html
- docs/packages/exporter.html
- docs/packages/exporter_test.html
- docs/packages/logging.html
- docs/packages/logging_test.html
- docs/packages/s3.html
- docs/packages/storage.html
- docs/packages/storage_test.html
- docs/packages/types.html
> Stub for documentation

- config.go
- docs/packages/config.html
- docs/packages/exporter.html
- docs/packages/exporter_test.html
- docs/packages/logging.html
- docs/packages/logging_test.html
- docs/packages/s3.html
- docs/packages/storage.html
- docs/packages/storage_test.html
- docs/packages/types.html
- s3.go
- storage.go
> Other minor fixes

- config.go
- config_test.go
- exporter.go
- s3.go
- storage.go
- storage_test.go
> Fixed minor issues

- README.md
- go.mod
Update Go version to 1.16
Done on CI
> Update Go version to 1.16

- .github/workflows/golangci-lint.yml
Fixed Golang CI setup
Done on CI
> Fixed Golang CI setup

- CODEOWNERS
> Code owners file

- docs/packages/storage.html
- storage.go
`.csv` extension for list of tables
Fixes #52
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
N/A
> `.csv` extension for list of tables

- exporter.go
- file.go
- storage.go
Ability to export to files
Fixes #28
Done on CI
> Ability to export to files

- goerrcheck.sh
Fix `goerrcheck`
Done on CI hopefully.
> Fix `goerrcheck`

- export_test.go
- exporter_test.go
- go.mod
- go.sum
Some unit tests for `exporter.go`
Done on CI
> Some unit tests for `exporter.go`

- exporter.go
- storage.go
Export metadata info CSV file
Fixes #54
N/A
> Export metadata info CSV file

- exporter.go
- storage.go
Export metadata into S3 or Minio
N/A
> Export metadata into S3 or Minio

- README.md
- exporter.go
- types.go
Export metadata on CLI flag
Fixes #57 
N/A
> Export metadata on CLI flag

- README.md
Example outputs generated by the tool
Fixes #31 
N/A
> Example outputs generated by the tool

- s3.go
Check parameters in `S3` module
N/A
> Check parameters in `S3` module

- go.mod
- go.sum
- storage.go
- storage_test.go
Storage unit tests for the `ReadRecordCount` function
Done on CI
> Storage unit tests for the `ReadRecordCount` function

- export_test.go
- s3_test.go
Unit tests for `s3` module
Fixes #35
Done on CI.
> Unit tests for `s3` module

- .travis.yml
Setup `Codecov.io` for this repository
- Other
Done on CI
> Setup `Codecov.io` for this repository

- storage_test.go
`Storage` unit tests
Done on CI
> `Storage` unit tests

- config.go
- config_test.go
> Minor change: config doc

- export_test.go
- exporter.go
- exporter_test.go
More unit tests for `exporter.go`
Done on CI.
> More unit tests for `exporter.go`

- export_test.go
- exporter_test.go
More unit tests for `exporter` module
Fixes #33
Done on CI
> More unit tests for `exporter` module

- README.md
- exporter.go
- exporter_test.go
- s3.go
- types.go
Ability to export operation log
Fixes #30 
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
Done on CI on basic level
> Operation log implementation

- export_test.go
- file_test.go
Unit tests for `file go`
Fixes #93 
Done on CI
> Unit tests for `file go`

- csv.go
- csv_test.go
Unit tests for `csv.go` module
Fixes #91 
Done on CI
> Unit tests for `csv.go` module

- types_test.go
> Types test (empty)

- csv.go
- csv_test.go
- storage.go
Refactoring table metadata export to CSV
Fixes #92
Done on CI
> Refactoring table metadata export to CSV

- README.md
Add Sentry to configuration variables to README.
> Update README with Sentry configuration

- exporter.go
- exporter_test.go
Fixed improper app name
Done on CI
> Fixed improper app name

- build_deploy.sh
- pr_check.sh
Needed to build the quay image and publish it.
> [CCXDEV-8122] Add build_deploy.sh

- pr_check.sh
Add stub tests for `pr_check.sh`. We don't have tests yet.
> Add stub tests

- file_test.go
Unit tests cleanup
Can be checked by `make test`
> Unit tests cleanup

- deploy/clowdapp.yaml
[app-interface!39785](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/39785) is already merged. Let's start by checking the S3 connection in stage.
- Run the job
> [CCXDEV-5895] Check the s3 connection in stage

- deploy/clowdapp.yaml
- s3.go
- s3_test.go
1. Fix a typo in the environment variable.
2. Ignore the port if not specified.
Unit tests.
> [CCXDEV-5895] Fix the connection with S3 in stage

- deploy/clowdapp.yaml
Our current configuration doesn't deploy jobs on updates to master. Let's try to generate a new job name each time.
> [CCXDEV-5895] Add CJI_RANDOM_SUFFIX

- deploy/clowdapp.yaml
The argument wasn't parsed correctly.
Tested in ccx-dev PSI.
> Fix clowdapp argument definition

- deploy/clowdapp.yaml
Increased the resources to avoid OOM.
> Fix job stage increasing resources

- deploy/clowdapp.yaml
1. Make the secrets optional so that they don't make the ephemeral release fail (the secrets doesn't exist in ephemeral envs).
2. Export the results to `file` so that the IRAE doesn't need any S3 connection. This can (will) be changed in the future to S3 using Minio in the ephemeral.
> [CCXDEV-5894] Update configuration to support ephemeral deployments

- deploy/clowdapp.yaml
Fixes:
```
8:03AM ERR Do selected operation error="Unknown output type: ${{OUTPUT}}"
```
> Fix output variable

- deploy/clowdapp.yaml
Let's export the whole database.
Deployment.
> [CCXDEV-6881] Dont limit the select

- README.md
- export_test.go
- exporter.go
- exporter_test.go
- gocyclo.sh
- types.go
Support for ignoring tables
Can be checked on CLI
> Support for ignoring tables

- storage.go
Lower memory consumption by resetting buffer + specifying size of Minio/S3 object directly.
Can be run locally etc.
> Lower memory consumption

- config_test.go
> Fixed typo

- csv_test.go
- file_test.go
- s3_test.go
- types_test.go
> Go fmted sources

- exporter.go
> Better empty string test

- storage_test.go
> Removed unused import

- Makefile
- README.md
Removed non-existing target
N/A
> Removed non-existing target

- README.md
> BDD tests doc

- deploy/cji.yml
- deploy/clowdapp.yaml
Distinguish the job and the instances' namesIn order to avoid collisions (and failure) when the post-deployment clowdjob invocation happens
> Distinguish CJI job and instance names

- deploy/clowdapp.yaml
Fix for distinct naming of the created objects.
N/A
> Distinct ccx-result-exporter object name depending on the target database

- deploy/cji.yml
- deploy/clowdapp.yaml
The CJI was pointing to a non existing resource.
None yet.
> Fix spec name

- deploy/clowdapp.yaml
Reverts RedHatInsights/insights-results-aggregator-exporter#152
> Revert "Temporal fix for wrong bucket name"

- deploy/clowdapp.yaml
export
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
- Benchmarks (no changes in the code)
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
> stage export

- deploy/clowdapp.yaml
> export now

- deploy/clowdapp.yaml
Use sharedDbNames instead of using the identifier name: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/45935
None yet.
> [CCXDEV-9132] Use clowder annotations for the exported db

- deploy/clowdapp.yaml
> [CCXDEV-9132] clowdapp - fix dependency name

- deploy/clowdapp.yaml
Remove the limit when exporting the data.
None yet.
> [CCXDEV-9132] Remove limit

- deploy/clowdapp.yaml
I forgot to add the default value in https://github.com/RedHatInsights/insights-results-aggregator-exporter/pull/171.
None.
> Set default limit to -1

- deploy/clowdapp.yaml
Update `TEST_DATE`  to run the job
> Run the job

- .github/workflows/golangci-lint.yml
- docs/packages/config.html
- docs/packages/config_test.html
- docs/packages/csv_test.html
- docs/packages/export_test.html
- docs/packages/exporter.html
- docs/packages/exporter_test.html
- docs/packages/file_test.html
- docs/packages/s3.html
- docs/packages/s3_test.html
- docs/packages/storage.html
- docs/packages/storage_test.html
- docs/packages/types.html
- docs/packages/types_test.html
GolangCI lint action v3
Done on CI
> GolangCI lint action v3

- docs/packages/config.html
- docs/packages/config_test.html
- docs/packages/csv_test.html
- docs/packages/export_test.html
- docs/packages/exporter.html
- docs/packages/exporter_test.html
- docs/packages/file_test.html
- docs/packages/s3.html
- docs/packages/s3_test.html
- docs/packages/storage.html
- docs/packages/storage_test.html
- docs/packages/types.html
- docs/packages/types_test.html
> Updated docs

- docs/ci.md
> Info about linters

- .travis.yml
Use the 'test-exporter' profile to start only the needed containers
- Behavioral tests (no changes in the code)
Local test
> Use specific profile in BDD tests

- exporter.go
Log a test error so that we can check GlitchTip works.
Logging.
> [CCXDEV-10346] Log a test error so that we can check glitchtip works

- deploy/cji.yml
- deploy/clowdapp.yaml
set a static app name to solve clowder deployment problem
- n/a
> set static app name

- deploy/clowdapp.yaml
> fix clowdapp.yaml indentation

- deploy/clowdapp.yaml
this could potentially prevent the job from running
n/a
> fix volume name

- go.mod
- go.sum
Bump-up `zerolog` library
To be done on CI.
> Bump-up zerolog library

- go.mod
- go.sum
Bump-up `pq` library
To be checked on CI
> Bump-up pq library

- exporter.go
- exporter_test.go
Pass `logger` instance via reference
To be done on CI
> Pass logger instance via reference

- go.mod
- go.sum
Bump-up `zerolog-sentry` library
> Bump-up zerolog-sentry library

- README.md
> Language badge

- go.mod
- go.sum
> Bump-up Minio library

- deploy/clowdapp.yaml
Export stage database to check problem with skipping old offsets
N/A
> Run exporter in stage

- .github/workflows/bdd.yaml
- .github/workflows/gotests.yaml
- .github/workflows/linters.yaml
- .github/workflows/shellcheck.yaml
Run the CI checks just one per PR push.
CI
> [CCXDEV-10102] Don't run the checks twice

- storage.go
- Minor improvement in `Storage` struct
- Better error logging
- Read support for sqlite3 (if needed)
> Minor improvement in `Storage` struct

- storage.go
- storage_test.go
- Ability to export metadata from SQLite database
- New unit tests
- Removed magic constants
> Ability to export metadata from SQLite database

- .github/workflows/linters.yaml
Splitting linters CI job
Fixes # [(issue)](https://issues.redhat.com/browse/CCXDEV-12634)
> Splitting linters job

- CODEOWNERS
[CCXDEV-14419] Remove CODEOWNERS file
Discussed [here](https://redhat-internal.slack.com/archives/C01A4DTTZN1/p1726665411138319)
> [CCXDEV-14419] Remove CODEOWNERS file

- .github/workflows/bots-automerge.yml
- renovate.json
Github-Actions to approve/automerge konflux PRs
> [CCXDEV-14176] Use Github-Actions to approve/automerge konflux PRs

- .github/workflows/bots-automerge.yml
Cleanup GH actions for merging konflux PRs.
> [CCXDEV-14404] Cleanup Fix GH actionts for konflux automerge.

- .github/workflows/bdd.yaml
- .github/workflows/gotests.yaml
- .github/workflows/linters.yaml
- goconst.sh
- gocyclo.sh
Includes a change in scripts to run gocyclo and goconst to fix the installation with newer go versions
> Run CI with GO 1.23 and tests also with 1.24

- deploy/clowdapp.yaml
Adding ENV variable to be able to enable glitchtip for aggregator-exporter.
Also changing the name of glitchtip dsn secret
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
> Enabling Glitchtip for aggregator exporter
