RedHatInsights/insights-results-aggregator-exporter

README.md, csv.go, exporter.go, file.go, s3.go, storage.go, storage_test.go, types.go
Ability to export rules disabled by multiple users
Fixes #68
Done on CI
=> Export rules disabled by multiple users

Makefile, check_coverage.sh
The `check_coverage.sh` didn't exist + openapi checks are not relevant here.
Manually.
=> Fix before commit

deploy/clowdapp.yaml
I was using "--" and only "-" is accepted: (https://kubernetes.io/docs/concepts/overview/working-with-objects/names/). Stage is broken because of this.
=> Use a valid name for the CJI

deploy/clowdapp.yaml
Invalid value: "string": spec.jobs.activeDeadlineSeconds in body must be of type integer: "string"
=> Fix int type

file_test.go
Fixed: ioutil.ReadFile is deprecated
Done on CI
=> Fixed: ioutil.ReadFile is deprecated

README.md, config.go, config.toml, config_test.go, deploy/clowdapp.yaml, export_test.go, exporter.go, exporter_test.go, tests/config2.toml
Configurable prefix for S3 destination bucket.
Using the INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__PREFIX environment variable, we can define an output path with the {PREFIX}/_metadata.csv format
- Updated UTs
=> Add configurable prefix for S3 bucket

deploy/clowdapp.yaml
Bucket name can only contain characters 0-9a-Z
=> Temporal fix for wrong bucket name

config.toml, export_test.go, exporter.go, exporter_test.go, storage.go
The previous commit was using the prefix in the bucket name, which is not allowed. With this change, the objects created within the bucket are appended with the correct prefix
Fixes #149 
Change has been tested using [awslocal](https://github.com/localstack/awscli-local), creating buckets with and without prefixes to ensure it works as expected.
BDD tests. under development.
=> Fix S3 destination paths depending on the target database

deploy/cji.yml
We are seeing an error in the [app-interface CI](https://ci.int.devshift.net/job/service-app-interface-gl-pr-check/153693/console):
```
10:48:05 [2022-08-09 08:48:05] [ERROR] [saasherder.py:populate_desired_state_saas_file:1153] - [crcs02ue1/ccx-data-pipeline-stage] desired item already exists: ClowdJobInvocation/ccx-data-pipeline-job-launcher. saas file name: ccx-data-pipeline-post-deploy-jobs, resource template name: insights-notification-exporter-cji.
```
I can see 2 reasons why it's failing (at least):
1. we have 2 CJI with the same name: one from stage and other for prod
2. the old CJIs are not deleted so each time we deploy a new version, the CJI has the same name as a previous one, so it cannot be deployed
Adding a random suffix will make the name unique.
Trying to fix #CCXDEV-8886 …
=> [CCXDEV-8886] Use a random CJI suffix

.github/workflows/golangci-lint.yml, file_test.go
`io.TempDir` is depreacted: [see](https://cs.opensource.google/go/go/+/go1.19:src/io/ioutil/tempfile.go;l=39).
Unit tests.
=> Dont use io.TempDir

deploy/cji.yml, deploy/clowdapp.yaml
kubernetes support only 63 characters for resource names. Some autogenerated names exceed that limit
Fixes ...
n/a
=> name too long fix

deploy/clowdapp.yaml
To be able use clowder's  'sharedDbAppName' the clowder dependencies should be properly set.
=> [CCXDEV-9132] clowdapp - set proper dependencies

Dockerfile
In order to fix some CVE the team decided to point to specific base images, so we can unsure that we use an specific version (and force the rebuild of the image) that already fix the CVE problem
- Security fix in dependent library (no changes in the code)
Built image locally
=> Using latest tagged go-toolset:1.17 base image

deploy/clowdapp.yaml
Update the Sentry DSN with the new one (GlitchTip)
Part of #[CCXDEV-10346](https://issues.redhat.com/browse/CCXDEV-10346)
- Migration
None yet, but it was working with the previous secret. We need to deploy it in stage and see if the secret can be read.
=> [CCXDEV-10346] Migrate from Sentry to GlitchTip

storage.go, storage_test.go
`org_id` is string, not int... adding quotation marks to the `WHERE org_id IN (%v)` query append
`make test`
=> fix selective export query, org_id is STRING not INT

ephemeral_import.sh
- wait for DB migrations to finish (waits until db-writer pod is in a `Ready` state, it will not be Ready until all init containers finish (`execute-migrations-init` container has to finish successfully, otherwise db-writer won't be Ready)
- fix a case when a user has more than 1 existing namespace and doesn't want to use the first one (cannot easily tell which is older/newer because `bonfire` sorts the namespaces alphabetically)
- load `EPH_NAMESPACE` from exported env var, if any, to bypass new namespace reservation
run the script with the above cases
=> improve ephemeral_import.sh script

.github/workflows/golangci-lint.yml, config.go, config_test.go, exporter.go, s3.go, s3_test.go, storage_test.go
Enable more linters on CI
To be done on CI.
=> Enable more linters on CI

storage.go
Fix newest `goconst` issue: remove duplicated string literal
=> Fix newest `goconst` issue: remove duplicated string literal

.github/workflows/bdd.yaml, .github/workflows/gotests.yaml, .github/workflows/linters.yaml, Dockerfile, build.sh, go.mod
- Bump Go version to 1.20
- Use ubi9 as base image (already tested in other services)
CI
=> Update go version to 1.20

.github/workflows/linters.yaml, storage.go, storage_test.go
this is causing issues when trying to export regular tables.
PR disables the selection of `dvo.*` tables.
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
=> Dbily dont export dvo
